#!/bin/bash
set -e

GIT_SHA_TAG="$(git rev-parse --short HEAD)"
docker tag $IMAGE_NAME "$DOCKER_REPO:$GIT_SHA_TAG"
DATE_TAG=$(date "+%Y.%m.%d.%H%M")
docker tag $IMAGE_NAME "$DOCKER_REPO:$DATE_TAG"
docker push $DOCKER_REPO

